"""Build the Analysis and Results Report: every analysis and every estimate.

Generated entirely from output/tables, so it always matches the current run.
Writes docs/analysis_report.md and docs/analysis_report.docx.
"""

from pathlib import Path

import numpy as np
import pandas as pd
import pypandoc

ROOT = Path(__file__).resolve().parents[1]
TAB = ROOT / "output" / "tables"
DOCS = ROOT / "docs"


def fmt(x, d=4):
    if pd.isna(x):
        return ""
    return f"{x:.{d}f}".replace("-", "−")


def stars(b, se):
    t = abs(b / se) if se else 0
    return "***" if t > 2.576 else "**" if t > 1.96 else "*" if t > 1.645 else ""


def md_table(df, floatfmt=3):
    cols = list(df.columns)
    lines = ["| " + " | ".join(str(c) for c in cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        cells = []
        for c in cols:
            v = r[c]
            cells.append(fmt(v, floatfmt) if isinstance(v, (float, np.floating)) else str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n\n" + "\n".join(lines) + "\n\n"  # pandoc needs blank lines around tables


def irf_table(est, rq, cumulative, term="shock", d=4):
    """One row per (spec, outcome); columns h = 0..12 with beta(se) and stars."""
    q = est[(est.rq == rq) & (est.cumulative == cumulative) & (est.term == term)].copy()
    if q.empty:
        return "_(none)_"
    q["cell"] = [f"{fmt(b, d)}{stars(b, s)} ({fmt(s, d)})" for b, s in zip(q.beta, q.se)]
    w = q.pivot_table(index=["spec", "outcome", "shock"], columns="h", values="cell", aggfunc="first")
    n = q.groupby(["spec", "outcome", "shock"]).agg(nobs_h0=("nobs", "first"), units=("n_units", "first"))
    w = w.join(n).reset_index()
    w.columns = [f"h={c}" if isinstance(c, (int, np.integer)) else c for c in w.columns]
    return md_table(w)


def main():
    DOCS.mkdir(exist_ok=True)
    est = pd.read_csv(TAB / "estimates.csv")
    out = []
    a = out.append
    a("---\ntitle: \"Analysis and Results Report\"\nsubtitle: \"Who Pays for Oil Shocks? — every analysis and every estimate\"\n"
      "date: \"Generated by scripts/10_analysis_report.py from output/tables\"\n---\n")
    a("""# 1. How to read this report

This report lists every analysis carried out in the study and every estimate it produced, in the order the
analyses were run. It is generated from the output tables, so its numbers always match the current run of
`./run_all.sh`.

**Units and conventions.**

- All changes are 100 × Δln, so a coefficient is the change in percentage points (pp) per 1% change in the fuel index.
- *Per-horizon* responses (β_h) are effects on the one-month change at horizon *h*. *Cumulative* responses are effects on
  the price level after *h* months.
- Gap = ln(CPI all income / CPI bottom 30%). A negative response means the bottom 30% face larger price increases
  (regressive); a positive response means the average household does (progressive).
- Standard errors in parentheses. \\*, \\*\\*, \\*\\*\\*: significant at 10%, 5%, 1% (two-sided, normal critical values).
  Bands in figures are 90%.
- National models: Newey–West standard errors with h + 1 lags. Regional panel: region fixed effects, Driscoll–Kraay
  standard errors. EU validation: country fixed effects, clustered (or robust) standard errors.
- "nobs_h0" is the number of observations in the h = 0 regression; "units" is 1 for national models and the number of
  regions or countries for panels.

**Status of each analysis.** *Pre-registered*: specified in the decision log before any estimate was produced
(replication gate; RQ1–RQ4 and robustness). *Supplementary*: specified after the first results (RQ3b, sub-period
splits, 2026 episode E1–E4). *Descriptive*: no model (Objective 1 statistics; 2026 decomposition E5).

**Analysis index.**

| # | Analysis | Script | Status | Section |
|---|---|---|---|---|
| A0 | Simulation test of the estimator | tests/test_lp.py | Validation | 2.1 |
| A1 | Replication gate on EU data (G1–G3) | scripts/04_replicate.py | Pre-registered | 2.2 |
| A2 | Descriptive statistics and trends (Objective 1) | scripts/09_descriptive.py | Descriptive | 3 |
| A3 | RQ1 pass-through, national | scripts/05_estimate.py | Pre-registered | 4.1 |
| A4 | RQ2 distributional gap, national | scripts/05_estimate.py | Pre-registered | 4.2 |
| A5 | RQ3 CPI divisions and weight decomposition | scripts/05_estimate.py | Pre-registered | 4.3 |
| A6 | RQ3b bottom-30% vs all-income components; sub-period splits | scripts/05_estimate.py | Supplementary | 4.4 |
| A7 | RQ4 regional panel and group interactions | scripts/05_estimate.py | Pre-registered | 4.5 |
| A8 | Robustness (a)–(l), including leave-one-region-out | scripts/05_estimate.py | Pre-registered | 4.6 |
| A9 | E1 out-of-sample test of the 2026 shock | scripts/07_episode_2026.py | Supplementary | 5.1 |
| A10 | E2–E3 regional burden and peso cost, 2026 | scripts/07_episode_2026.py | Supplementary | 5.2 |
| A11 | E4 mechanism: household fuels, fares, cereals | scripts/07_episode_2026.py | Supplementary | 5.3 |
| A12 | E5 decomposition of the 2026 gap | scripts/07_episode_2026.py | Descriptive | 5.4 |
""")

    # 2 validation
    a("# 2. Validation\n\n## 2.1 Simulation test (A0)\n")
    a("""Data are simulated from y_t = 0.4·y_{t−1} + 0.04·x_t + 0.02·x_{t−1} + 0.01·x_{t−2} + e_t (x ~ N(0, 3²),
e ~ N(0, 0.2²)), whose impulse response is known exactly (0.040, 0.036, 0.0244, …). The tests in `tests/test_lp.py`
require the estimator to recover it within 0.006 at h = 0..6 for (i) a single long series with Newey–West errors,
(ii) a 20-unit panel with clustered errors and (iii) the same with Driscoll–Kraay errors; to recover the cumulative
response within 0.01; and to estimate a known group difference of 0.03 within 0.005. All five tests pass in every
run of `./run_all.sh`.
""")
    rep = pd.read_csv(TAB / "replication_eu_ph.csv")
    gate = pd.read_csv(TAB / "replication_gate.csv")
    a("## 2.2 Replication gate (A1)\n\nPre-registered criteria are in the decision log (CLAUDE.md). Result:\n")
    a(md_table(gate.rename(columns={gate.columns[0]: "test"})))
    a("\n\nPer-horizon responses (EU: country fixed effects; PH: Newey–West):\n")
    rep["cell"] = [f"{fmt(b, 4)}{stars(b, s)} ({fmt(s, 4)})" for b, s in zip(rep.beta, rep.se)]
    w = rep.pivot_table(index="spec", columns="h", values="cell", aggfunc="first")
    w = w.join(rep.groupby("spec").agg(nobs=("nobs", "first"), units=("n_units", "first"))).reset_index()
    w.columns = [f"h={c}" if isinstance(c, (int, np.integer)) else c for c in w.columns]
    a(md_table(w))
    tg = pd.read_csv(ROOT / "replication" / "kpodar_liu_2021_targets.csv")
    a("\n\nReference values transcribed from Kpodar and Liu (2021), Annex Tables 1–2 and Figures 7 and 10:\n")
    a(md_table(tg, 3))

    # 3 descriptive
    a("\n\n# 3. Descriptive statistics and trend analysis (A2, Objective 1)\n")
    for f, title in [("desc_summary", "3.1 Summary statistics of monthly changes (100 × Δln), national"),
                     ("desc_annual", "3.2 Annual inflation (average of monthly year-on-year rates)"),
                     ("desc_episodes", "3.3 Fuel-shock episodes (≥ 3 months with fuel ≥ +15% y/y)"),
                     ("desc_crosscorr", "3.4 Cross-correlations: fuel change at t with price change at t + k"),
                     ("desc_regional", "3.5 Regional summary"),
                     ("desc_adf", "3.6 Augmented Dickey–Fuller tests")]:
        a(f"\n## {title}\n\n")
        a(md_table(pd.read_csv(TAB / f"{f}.csv"), 3))
    a("\n\n![Trends: inflation by group, gap and fuel index](../output/figures/figd1_trends.png){width=95%}\n")
    a("\n![Regional averages and cumulative gap](../output/figures/figd2_regional.png){width=95%}\n")

    # 4 estimates
    a("\n# 4. Local projection estimates (Objective 2)\n")
    a("\nEach table: one row per specification; cells are β (s.e.) at each horizon.\n")
    sections = [("RQ1", "4.1 RQ1: pass-through to all-income and bottom-30% prices (A3)"),
                ("RQ2", "4.2 RQ2: distributional gap, national (A4)"),
                ("RQ3", "4.3 RQ3: CPI divisions, all income (A5)"),
                ("RQ3b", "4.4 RQ3b and sub-period splits (A6, supplementary)"),
                ("RQ4", "4.5 RQ4: regional panel and group interactions (A7)"),
                ("ROB", "4.6 Robustness (A8)")]
    for rq, title in sections:
        a(f"\n## {title}\n")
        terms = sorted(est[est.rq == rq].term.unique(), key=lambda x: (x != "shock", x))
        for term in terms:
            lab = "" if term == "shock" else f" — coefficient on {term} (additional effect in the group)"
            a(f"\n**Cumulative responses{lab}**\n\n")
            a(irf_table(est, rq, True, term))
            a(f"\n\n**Per-horizon responses{lab}**\n\n")
            a(irf_table(est, rq, False, term))
            a("\n")
        if rq == "RQ3":
            a("\n**Weight decomposition (cumulative response at h = 12 × weight difference)**\n\n")
            a(md_table(pd.read_csv(TAB / "rq3_gap_decomposition.csv", dtype={"coicop": str}), 4))
            a("\n")
        if rq == "RQ4":
            a("\n**Region groups used in the interactions**\n\n")
            a(md_table(pd.read_csv(TAB / "region_groups.csv"), 2))
            a("\n")
    for fig, cap in [("fig1_rq1_passthrough", "RQ1 cumulative pass-through"),
                     ("fig2_rq2_rq4_ratio", "RQ2/RQ4 gap, national and panel"),
                     ("fig3_rq3_components", "RQ3 divisions"), ("fig4_rq4_groups", "RQ4 group interactions"),
                     ("fig5_robustness", "Robustness of the six-month gap")]:
        a(f"\n![{cap}](../output/figures/{fig}.png){{width=85%}}\n")

    # 5 2026
    a("\n# 5. The 2026 shock (Objective 3)\n")
    a("\n## 5.0 Context: year-on-year inflation, late 2025–2026\n\n")
    a(md_table(pd.read_csv(TAB / "context_2026.csv"), 2))
    for f, title, d in [("e1_national_2026", "5.1 E1 out-of-sample test (model estimated to Dec 2025)", 3),
                        ("e2_regional_2026", "5.2 E2–E3 regional fuel-driven rise and peso cost", 2),
                        ("e4_mechanism", "5.3 E4 mechanism: household fuels, fares and cereals (2013–2026)", 4),
                        ("e5_decomposition_2026", "5.4 E5 decomposition of the Dec 2025–Aug 2026 rise", 3)]:
        a(f"\n## {title}\n\n")
        a(md_table(pd.read_csv(TAB / f"{f}.csv"), d))
    a("\n\nE1 columns: beta = fuel-driven change (100 × log points since Dec 2025); lo/hi = indicative range combining "
      "the per-horizon 90% bounds; actual = observed change. E2 columns: fuel_driven_* = fuel-driven rise by Aug 2026; "
      "extra_cost_php_month = fuel-driven cost for a poverty-line family of five. E5: weight and percentage change "
      "of each item in each basket and its contribution (pp) to the basket's rise; gap_pp = bottom 30% minus all income.\n")
    for fig, cap in [("fig6_2026_out_of_sample", "2026 actual vs fuel-driven"),
                     ("fig7_2026_gap_decomposition", "Decomposition of the 2026 gap")]:
        a(f"\n![{cap}](../output/figures/{fig}.png){{width=85%}}\n")

    a("\n# 6. Output files\n\n| File | Contents |\n|---|---|\n")
    for f in sorted(TAB.glob("*.csv")) + sorted(TAB.glob("*.json")):
        a(f"| output/tables/{f.name} | {DESCR.get(f.stem, '')} |\n")

    text = "".join(out)
    (DOCS / "analysis_report.md").write_text(text)
    pypandoc.convert_text(text, "docx", format="markdown", outputfile=str(DOCS / "analysis_report.docx"),
                          extra_args=[f"--resource-path={DOCS}:{ROOT}", "--toc", "--toc-depth=2"])
    print("wrote docs/analysis_report.md and .docx")


DESCR = {
    "estimates": "All local projection estimates (RQ1–RQ4, RQ3b, robustness): spec, outcome, shock, cumulative flag, h, term, beta, se, 90% bounds, nobs, units, R²",
    "replication_eu_ph": "Replication gate estimates (EU) and indicative Philippine estimate",
    "replication_gate": "Pass/fail of the pre-registered gate criteria",
    "rq3_gap_decomposition": "RQ3 division responses at h = 12 with basket weights and implied gap contributions",
    "region_groups": "Poverty, food share and group dummies for the 17 regions",
    "context_2026": "Year-on-year inflation (both groups) and fuel, Oct 2025–Aug 2026",
    "e1_national_2026": "E1 fuel-driven vs actual change, national, Jan–Aug 2026",
    "e2_regional_2026": "E2–E3 regional fuel-driven rise, actual rise, poverty line and peso cost",
    "e4_mechanism": "E4 responses and weights of household fuels, fares and cereals, both baskets",
    "e5_decomposition_2026": "E5 item contributions to the Dec 2025–Aug 2026 rise, both baskets",
    "desc_summary": "Objective 1 summary statistics by period",
    "desc_annual": "Objective 1 annual inflation and fuel change",
    "desc_episodes": "Objective 1 fuel-shock episodes",
    "desc_crosscorr": "Objective 1 cross-correlations",
    "desc_regional": "Objective 1 regional summary",
    "desc_adf": "Objective 1 unit-root tests",
    "desc_yoy_national": "Monthly year-on-year series used in the trend figure",
    "paper_numbers": "Every number inserted into the manuscript and working paper",
}

if __name__ == "__main__":
    main()
